import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      link: { type: 'doc', id: 'index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
};

export default sidebars;
